---
- name: Install OpenCV 4.10.0 on Raspberry Pi
  hosts: raspi
  become: true
  vars:
    opencv_version: "4.10.0"
    opencv_source_dir: "{{ ansible_env.HOME }}/opencv"
    opencv_source_zip: "{{ opencv_source_dir }}.zip"
    opencv_contrib_source_dir: "{{ ansible_env.HOME }}/opencv_contrib"
    opencv_contrib_source_zip: "{{ opencv_contrib_source_dir }}.zip"
    opencv_build_dir: "{{ ansible_env.HOME }}/opencv/build"
    opencv_install_dir: "/usr/local"
  tasks:
    - name: Ensure HOME directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}"
        state: directory
        mode: "0400"

    - name: Remove any existing OpenCV directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ opencv_source_dir }}"
        - "{{ opencv_source_zip }}"
        - "{{ opencv_contrib_source_dir }}"
        - "{{ opencv_contrib_source_zip }}"

    - name: Download OpenCV source code
      ansible.builtin.get_url:
        url: "https://github.com/opencv/opencv/archive/{{ opencv_version }}.zip"
        dest: "{{ ansible_env.HOME }}/opencv.zip"
        mode: "0755"

    - name: Download OpenCV contrib modules
      ansible.builtin.get_url:
        url: "https://github.com/opencv/opencv_contrib/archive/{{ opencv_version }}.zip"
        dest: "{{ ansible_env.HOME }}/opencv_contrib.zip"
        mode: "0755"

    - name: Unzip OpenCV source code
      ansible.builtin.unarchive:
        src: "{{ ansible_env.HOME }}/opencv.zip"
        dest: "{{ ansible_env.HOME }}/"
        remote_src: true

    - name: Unzip OpenCV contrib modules
      ansible.builtin.unarchive:
        src: "{{ ansible_env.HOME }}/opencv_contrib.zip"
        dest: "{{ ansible_env.HOME }}/"
        remote_src: true

    - name: Rename OpenCV directories for consistency
      ansible.builtin.command:
        cmd: "mv {{ ansible_env.HOME }}/opencv-{{ opencv_version }} {{ opencv_source_dir }}"
      args:
        creates: "{{ opencv_source_dir }}"
      changed_when: false

    - name: Rename OpenCV contrib directories for consistency
      ansible.builtin.command:
        cmd: "mv {{ ansible_env.HOME }}/opencv_contrib-{{ opencv_version }} {{ opencv_contrib_source_dir }}"
      args:
        creates: "{{ opencv_contrib_source_dir }}"
      changed_when: false

    - name: Create build directory
      ansible.builtin.file:
        path: "{{ opencv_build_dir }}"
        state: directory
        mode: "0755"

    - name: Check if CMake has already been run
      ansible.builtin.stat:
        path: "{{ opencv_build_dir }}/Makefile"
      register: cmake_result

    - name: Run CMake to configure the OpenCV build
      ansible.builtin.command:
        cmd: >
          cmake -D CMAKE_BUILD_TYPE=RELEASE
                -D CMAKE_INSTALL_PREFIX={{ opencv_install_dir }}
                -D OPENCV_EXTRA_MODULES_PATH={{ opencv_contrib_source_dir }}/modules
                -D ENABLE_NEON=ON
                -D WITH_OPENMP=ON
                -D WITH_OPENCL=OFF
                -D BUILD_TIFF=ON
                -D WITH_FFMPEG=ON
                -D WITH_TBB=ON
                -D BUILD_TBB=ON
                -D WITH_GSTREAMER=ON
                -D BUILD_TESTS=OFF
                -D WITH_EIGEN=OFF
                -D WITH_V4L=ON
                -D WITH_LIBV4L=ON
                -D WITH_VTK=OFF
                -D WITH_QT=OFF
                -D WITH_PROTOBUF=ON
                -D OPENCV_ENABLE_NONFREE=ON
                -D INSTALL_C_EXAMPLES=OFF
                -D INSTALL_PYTHON_EXAMPLES=OFF
                -D PYTHON3_PACKAGES_PATH=/usr/lib/python3/dist-packages
                -D OPENCV_GENERATE_PKGCONFIG=ON
                -D BUILD_EXAMPLES=OFF ..
      args:
        chdir: "{{ opencv_build_dir }}"
      register: cmake_output
      changed_when: cmake_output.stdout is search('Configuring done') or cmake_output.stdout is search('Generating done')
      when: not cmake_result.stat.exists

    - name: Check if OpenCV is already compiled
      ansible.builtin.stat:
        path: "{{ opencv_build_dir }}/lib/libopencv_core.so"
      register: opencv_compiled

    - name: Compile OpenCV (this may take several hours)
      ansible.builtin.command:
        cmd: make -j4
      args:
        chdir: "{{ opencv_build_dir }}"
      register: compile_result
      changed_when:
        - compile_result.rc == 0
        - "'Built target opencv_core' in compile_result.stdout"  # Positive confirmation
      when: not opencv_compiled.stat.exists

    - name: Check if OpenCV is already installed
      ansible.builtin.stat:
        path: "{{ opencv_install_dir }}/lib/libopencv_core.so"
      register: opencv_installed

    - name: Install OpenCV
      ansible.builtin.command:
        cmd: "make install"
      args:
        chdir: "{{ opencv_build_dir }}"
      register: install_result
      changed_when: install_result.stdout_lines | length > 0
      when: not opencv_installed.stat.exists

    - name: Update shared library cache
      ansible.builtin.command: "ldconfig"
      register: ldconfig_result
      changed_when: false  # ldconfig doesn't provide useful output for change detection

    - name: Clean up build files to free up space
      ansible.builtin.command:
        cmd: "make clean"
      args:
        chdir: "{{ opencv_build_dir }}"
      register: clean_result
      changed_when: clean_result.stdout is search('Cleaning') or clean_result.stdout is search('removed')

    - name: Check if OpenCV is installed
      ansible.builtin.package_facts:
        manager: auto

    - name: Display OpenCV installation status
      ansible.builtin.debug:
        msg: "OpenCV is {{ 'installed' if 'opencv' in ansible_facts.packages else 'not installed' }}"
