---
- name: Install OpenCV Dependencies Based on Debian Version
  hosts: raspi
  become: true
  tasks:
    - name: Gather OS distribution information
      ansible.builtin.setup:
        gather_subset: distribution

    - name: Set Debian version
      ansible.builtin.set_fact:
        debian_version: "{{ ansible_facts['distribution_version'] | regex_replace('\\..*', '') }}"

    - name: Display detected Debian version
      ansible.builtin.debug:
        msg: "Detected Debian {{ debian_version }}"

    - name: Install common dependencies
      ansible.builtin.apt:
        name:
          - build-essential
          - cmake
          - git
          - unzip
          - pkg-config
          - libjpeg-dev
          - libtiff-dev
          - libpng-dev
          - libavcodec-dev
          - libavformat-dev
          - libswscale-dev
          - libgtk2.0-dev
          - libgtk-3-dev
          - libgstreamer1.0-dev
          - gstreamer1.0-gtk3
          - libgstreamer-plugins-base1.0-dev
          - gstreamer1.0-gl
          - libxvidcore-dev
          - libx264-dev
          - python3-dev
          - python3-numpy
          - python3-pip
          - libv4l-dev
          - v4l-utils
          - libopenblas-dev
          - libatlas-base-dev
          - libblas-dev
          - liblapack-dev
          - gfortran
          - libhdf5-dev
          - libprotobuf-dev
          - libgoogle-glog-dev
          - libgflags-dev
          - protobuf-compiler
        state: present
        update_cache: true

    - name: Install additional dependencies for Debian 10 and 11
      ansible.builtin.apt:
        name:
          - libtbb2
          - libtbb-dev
          - libdc1394-22-dev
        state: present
      when: debian_version in ['10', '11']

    - name: Install additional dependencies for Debian 12
      ansible.builtin.apt:
        name:
          - libtbbmalloc2
          - libtbb-dev
          - libdc1394-dev
          - gstreamer1.0-libcamera
        state: present
      when: debian_version == '12'
