- name: Update and upgrade packages
  ansible.builtin.import_playbook: plays/apt_update_upgrade.yml

- name: Install OpenCV dependencies
  ansible.builtin.import_playbook: plays/install_opencv_dependencies.yml

- name: Download and build OpenCV from source
  ansible.builtin.import_playbook: plays/download_and_install_opencv.yml
