- name: Update and upgrade packages
  ansible.builtin.import_playbook: plays/apt_update_upgrade.yml

- name: Install OpenCV dependencies
  ansible.builtin.import_playbook: plays/install_opencv_dependencies.yml
