include(CheckCXXCompilerFlag)

function(enable_sanitizers)
    if(NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        return()
    endif()

    option(ENABLE_SANITIZER_ADDRESS "Enable address sanitizer" OFF)
    option(ENABLE_SANITIZER_UNDEFINED "Enable undefined behavior sanitizer" OFF)

    if(ENABLE_SANITIZER_ADDRESS)
        check_cxx_compiler_flag("-fsanitize=address" HAS_ASAN)
        if(HAS_ASAN)
            add_compile_options(-fsanitize=address)
            link_libraries(-fsanitize=address)
        endif()
    endif()

    if(ENABLE_SANITIZER_UNDEFINED)
        check_cxx_compiler_flag("-fsanitize=undefined" HAS_UBSAN)
        if(HAS_UBSAN)
            add_compile_options(-fsanitize=undefined)
            link_libraries(-fsanitize=undefined)
        endif()
    endif()
endfunction()
